version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0-apache-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: curl -sS https://getcomposer.org/installer | php
      - run: mv composer.phar /usr/local/bin/composer
      - run: composer install
      - run:
          name: Build WordPress image
          command: |
            docker build -t wordpress:latest .
      - run:
          name: Run WordPress container
          command: |
            docker run -d -p 8000:80 --name wordpress wordpress:latest
      - run:
          name: Run tests
          command: |
            curl -sS http://localhost:8000/wp-admin/install.php
            # Run WordPress tests here
  cleanup:
    docker:
      - image: circleci/php:7.4-apache-node-browsers
    steps:
      - run:
          name: Stop WordPress container
          command: |
            docker stop wordpress
      - run:
          name: Remove WordPress container
          command: |
            docker rm wordpress
      - run:
          name: Remove WordPress image
          command: |
            docker rmi wordpress:latest
