version: 2.1
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run:
          name: Add Git to PATH
          command: export PATH="/usr/local/git/bin:$PATH"
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t wordpress .
      - run:
          name: Run Docker container
          command: |
            docker run -d -p 8080:80 wordpress
            sleep 10
      - run:
          name: Run WordPress installation
          command: |
            curl -X POST \
              --data "weblog_title=My WordPress Site&user_name=admin&admin_password=admin&admin_password2=admin&admin_email=admin@example.com" \
              http://localhost:8080/wp-admin/install.php?step=2
      - run:
          name: Run WordPress tests
          command: |
            docker exec -it $(docker ps -qf "ancestor=wordpress") /bin/sh -c "cd wp-content/plugins/test-bundle && composer install && vendor/bin/wp-cli test run"
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Authenticate with Google Cloud
          command: |
            gcloud auth activate-service-account --key-file=<path-to-key-file>
      - run:
          name: Deploy to Google Cloud
          command: |
            gcloud config set project <your-project-id>
            gcloud app deploy app.yaml --quiet
