version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-apache-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: apt-get update && apt-get install -y apt-utils
      - run: apt-get install -y unzip
      - run: curl -sS https://getcomposer.org/installer | php
      - run: mv composer.phar /usr/local/bin/composer
      - run: composer install
      - run:
          name: Build WordPress image
          command: |
            docker build -t my-wordpress-image .
      - run:
          name: Run WordPress container
          command: |
            docker run -d -p 8000:80 --name my-wordpress-container my-wordpress-image
      - run:
          name: Run tests
          command: |
            curl -sS http://localhost:8000/wp-admin/install.php
            # Run WordPress tests here
  cleanup:
    docker:
      - image: circleci/php:7.4-apache-node-browsers
    steps:
      - run:
          name: Stop WordPress container
          command: |
            docker stop my-wordpress-container
      - run:
          name: Remove WordPress container
          command: |
            docker rm my-wordpress-container
      - run:
          name: Remove WordPress image
          command: |
            docker rmi my-wordpress-image
