version: 2.1
jobs:
  build:
    working_directory: ./wordpress/html
    docker:
      - image: docker:stable
      - image: wordpress:latest

    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress_db
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=user_password

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build WordPress Docker image
          command: |
            docker build -t wordpress:latest .
          environment:
            DOCKER_BUILDKIT: 1
      - run:
          name: Run WordPress Docker container
          command: |
            docker run --name wordpress -p 8080:80 -d wordpress:latest
      - run:
          name: Run WordPress installation
          command: |
            docker exec -it wordpress /bin/bash -c "curl -O https://wordpress.org/latest.tar.gz && tar -xzf latest.tar.gz && mv wordpress/* /var/www/html && rm latest.tar.gz"
      - run:
          name: Run WordPress tests
          command: |
            composer install
            phpunit
  