version: 2.1

jobs:
  build:
    docker:
      # Use the official WordPress Docker image
      - image: wordpress:latest
        environment:
          WORDPRESS_DB_HOST: 127.0.0.1:3306
          WORDPRESS_DB_NAME: my_wordpress_db
          WORDPRESS_DB_USER: my_wordpress_user
          WORDPRESS_DB_PASSWORD: my_wordpress_password
          WORDPRESS_CONFIG_EXTRA: |
            define('WP_DEBUG', true);
            define('WP_DEBUG_LOG', true);
            define('WP_DEBUG_DISPLAY', false);
            define('SCRIPT_DEBUG', true);

      # Add MySQL container for database
      - image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: my_mysql_root_password
          MYSQL_DATABASE: my_wordpress_db
          MYSQL_USER: my_wordpress_user
          MYSQL_PASSWORD: my_wordpress_password

    steps:
      - checkout

      # Install dependencies for WordPress tests
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y libpng-dev libjpeg-dev libxml2-dev libfreetype6-dev libzip-dev
            docker-php-ext-configure gd --with-freetype --with-jpeg
            docker-php-ext-install -j "$(nproc)" gd mysqli pdo_mysql zip xmlrpc soap

      # Run the WordPress unit tests
      - run:
          name: Run Unit Tests
          command: |
            cd wp-content/plugins/my-plugin
            bash bin/install-wp-tests.sh wordpress_test my_wordpress_user my_wordpress_password localhost latest
            phpunit
