version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.5
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            apk add --no-cache py-pip=20.3.4-r1 && \
            pip install docker-compose==1.28.5
      - run:
          name: Build and start Docker Compose services
          command: |
            docker-compose up --build -d
      - run:
          name: Wait for WordPress to start
          command: |
            until $(curl --output /dev/null --silent --head --fail http://localhost); do
              printf '.'
              sleep 5
            done
      - run:
          name: Run WordPress tests
          command: |
            docker-compose run --rm wordpress sh -c "cd wp-content/plugins/ && \
            git clone https://github.com/wp-cli/test-bundle.git && \
            cd test-bundle && \
            composer install --prefer-source --no-interaction && \
            composer test"
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - run:
          name: Deploy to Google Cloud
          command: |
            gcloud config set project <your-project-id> && \
            gcloud auth activate-service-account --key-file <path-to-key-file> && \
            gcloud app deploy app.yaml --quiet
