version: 2.1

jobs:
  test:
    working_directory: ~/project
    macos:
      xcode: "12.5.1"
    docker:
      - image: php:7.4-apache
        environment:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: example
          WORDPRESS_DB_NAME: wordpress_test
        ports:
          - "8000:80"
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: wordpress_test
          MYSQL_ROOT_PASSWORD: example
        ports:
          - "3306:3306"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            docker run --rm -v "$(pwd):/var/www/html" php:7.4-apache bash -c "apt-get update && apt-get install -y git curl && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && composer install"
      - run:
          name: Run WordPress installation
          command: |
            docker run --rm -v "$(pwd):/var/www/html" --network circleci_mysql_network -e WORDPRESS_DB_HOST=mysql -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_PASSWORD=example -e WORDPRESS_DB_NAME=wordpress_test php:7.4-apache bash -c "wp core download && wp config create --dbname=wordpress_test --dbuser=root --dbpass=example --dbhost=mysql --extra-php=\"define( 'WP_DEBUG', true );\" && wp core install --url=http://localhost:8000 --title='WordPress' --admin_user=admin --admin_password=admin --admin_email=admin@example.com"
      - run:
          name: Run WordPress tests
          command: |
            docker run --rm -v "$(pwd):/var/www/html" php:7.4-apache bash -c "wp scaffold plugin-tests my-plugin && cd wp-content/plugins/my-plugin && composer install && WP_TESTS_DIR=/tmp/wordpress-tests-lib/includes WP_CORE_DIR=/var/www/html bash bin/install-wp-tests.sh wordpress_test root example localhost latest && vendor/bin/phpunit"
