version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: docker:stable
      - image: wordpress:latest

    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wordpress

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build WordPress Docker image
          command: |
            docker build -t wordpress:latest .
          environment:
            DOCKER_BUILDKIT: 1
      - run:
          name: Run WordPress Docker container
          command: |
            docker run --name wordpress -p 8080:80 -d wordpress:latest
      - run:
          name: Run WordPress installation
          command: |
            docker exec -it wordpress /bin/bash -c "curl -O https://wordpress.org/latest.tar.gz && tar -xzf latest.tar.gz && mv wordpress/* /var/www/html && rm latest.tar.gz"
      - run:
          name: Run WordPress tests
          command: |
            composer install
            phpunit
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Authenticate with Google Cloud
          command: |
            gcloud auth activate-service-account --key-file=<path-to-key-file>
      - run:
          name: Deploy to Google Cloud
          command: |
            gcloud config set project <your-project-id>
            gcloud app deploy app.yaml --quiet
