version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Composer Dependencies
          command: |
            composer install --no-interaction
      - run:
          name: Start MySQL Service
          command: brew services start mysql
      - run:
          name: Create MySQL Database
          command: mysql -e 'CREATE DATABASE wordpress;'
      - run:
          name: Install WordPress
          command: |
            wp core download --path=./wordpress/html
            wp config create --dbname=wordpress_db --dbuser=user
            wp core install --url=http://localhost --title=zzk --admin_user=admin --admin_password=password --admin_email=nickenchao@gmail.com --path=./wordpress/html
      - run:
          name: Run PHPUnit Tests
          command: |
            cd wordpress/wp-content/plugins/my-plugin
            ./vendor/bin/phpunit
