version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7-jessie-browsers-legacy

    steps:
      - checkout
      - deploy:
          command: |
            sudo pip install --upgrade pip
            fab -f ./fabfile.py

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master