version: 2.1
jobs:
  build:
    docker:
      - image: docker:stable

    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress_db
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=user_password

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build WordPress Docker image
          command: |
            docker build -t wordpress .
          environment:
            DOCKER_BUILDKIT: 1
      - run:
          name: Run Docker container
          command: |
            docker run -d -p 8080:80 wordpress
            sleep 10
      - run:
          name: Run WordPress installation
          command: |
            docker run --rm \
              -p 8080:80 \
              -e WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST \
              -e WORDPRESS_DB_USER=$WORDPRESS_DB_USER \
              -e WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD \
              -e WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME \
              my-wordpress-app:latest
      - run:
          name: Run WordPress tests
          command: |
            docker exec -it $(docker ps -qf "ancestor=wordpress") /bin/sh -c "cd wp-content/plugins/test-bundle && composer install && vendor/bin/wp-cli test run"
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Authenticate with Google Cloud
          command: |
            gcloud auth activate-service-account --key-file=<path-to-key-file>
      - run:
          name: Deploy to Google Cloud
          command: |
            gcloud config set project <your-project-id>
            gcloud app deploy app.yaml --quiet
